# Generated by Django 4.2.2 on 2024-09-26 08:56

from django.db import migrations

def create_data(apps, schema_editor):
    Baker = apps.get_model('niko', 'Baker')
    Baker(name="Joe Silver", email="joe@email.com", phone="00000000", photo='media/photo/baker.png').save()
    Baker(name="Kira Night", email="kira@email.com", phone="33333333", photo='media/photo/baker.png').save()

    Customer = apps.get_model('niko', 'Customer')
    Customer(name="Customer1", phone="00000000").save()
    Customer(name="Customer2", phone="33333333").save()

class Migration(migrations.Migration):

    dependencies = [
        ('niko', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
